### ISSUE TITLE
v1 NXM push and deprecate

### ISSUE THREAD

**Issue by rackstar** [NexusMutual/smart-contracts#1215]
## Overview

Relates to https://github.com/NexusMutual/smart-contracts/issues/1211

These are the gas cost estimates to push v1 NXM to users.

### Gas estimate / cost
CLA (59) - 2,505,458
- 3 gwei:  0.007516374 ETH
- 5 gwei:  0.01252729 ETH

Stake (305) - 26,646,603
- 3 gwei:  0.079939809 ETH
- 5 gwei:  0.133233015 ETH

Rewards (663) - 48,516,039
- 3 gwei:  0.145548117 ETH
- 5 gwei:  0.242580195 ETH

CN (1358) - 182,221,106
- 3 gwei:  0.546663318 ETH
- 5 gwei:  0.91110553 ETH

Total - 259,889,206
- 3 gwei: 0.779667618 ETH
- 5 gwei: 1.29944603 ETH

### Total NXM

Stake - 19841.923206371297099628 NXM
Rewards - 4324.917808889408910693 NXM
CLA - 2222.67024000000001 NXM
CN - 13479.635746436785782644 NXM

## Tasks

- [x] check the accounting does the NXM count matches with what is actually NXM in the system
- [x] implement push v1 NXM to users
- [x] fork test
- [x] push v1 NXM to users
- [x] verify v1 NXM is empty
- [ ] deprecate v1 NXM related methods once all v1 NXM have been pushed

**Comment by rackstar** [comment]
rough draft branch - https://github.com/NexusMutual/smart-contracts/tree/feat/v1-nxm

TODO:
* move scripts to [scripts repo](https://github.com/NexusMutual/scripts) and clean up
* keep fork test here in smart-contracts repo

**Comment by rackstar** [comment]
| Pool  | Deposits (ETH)                  | Rewards (ETH)                   |
|-------|---------------------------------|---------------------------------|
| 1     | 32,855.061601914421589825       | 2,685.349737626577337663        |
| 2     | 107,056.988892075349495257      | 2,347.540010495784871948        |
| 3     | 62,909.231427718665092814       | 216.753745323833097653          |
| 4     | 56,890.254530014654030726       | 752.515508971688508151          |
| 5     | 119,447.072978921479630138      | 7,548.897999626846826671        |
| 6     | 0.0                             | 0.0                             |
| 7     | 20.000000001277753131           | 0.174855684409108152            |
| 8     | 9,300.0                         | 82.261485534240277795           |
| 9     | 0.0                             | 0.0                             |
| 10    | 0.0                             | 0.0                             |
| 11    | 30,754.686006990108857918       | 1,231.977508770208205444        |
| 12    | 0.0                             | 0.0                             |
| 13    | 127.0                           | 1.979823977738460338            |
| 14    | 0.0                             | 0.0                             |
| 15    | 1.009999992336241613            | 0.010174365874272189            |
| 16    | 0.0                             | 0.000000000000000001            |
| 17    | 0.0                             | 0.000000000000000001            |
| 18    | 3,366.469999999985637997        | 52.118519315552816325           |
| 19    | 0.0                             | 0.0                             |
| 20    | 433.1121712465573               | 6.998604292903409353            |
| 21    | 0.0                             | 0.0                             |
| 22    | 20,616.587107128560883244       | 1,464.038914347343117083        |
| 23    | 30,000.0                        | 784.90975275353987718           |
| 24    | 500.01                          | 12.07345323327497783            |
| 25    | 40.0                            | 0.478119195194828792            |
| **Pools Stake/Rewards Total**  | **474,317.484716003396512663** | **17,188.078213515009992569**  |
| **CN Balance**  | **13,479.635746436787** |                                 |
| **CLA Balance** | **2,102.67024**         |                                 |
| **EXPECTED Total Pool Balance** | **507,087.868915955193505232** ETH |     |
| **ACTUAL Token Controller Balance** | **507,780.73694946** ETH         |     |
| **Difference**  | **+692.868033504806494768** ETH |                        |

**Comment by rackstar** [comment]
![Image](https://github.com/user-attachments/assets/e6caf182-b21b-48fb-b69d-73461e48593c)
https://docs.google.com/spreadsheets/d/1r65VtVdWzf6L0gK3vB0myxecwl6xhb48RMRjw8Aj69c/edit?gid=0#gid=0

**Comment by rackstar** [comment]
closing.
