### ISSUE TITLE
EPIC: Smart Contract Documentation

### ISSUE THREAD

**Issue by rackstar** [NexusMutual/smart-contracts#1296]
## Overview

We need to write documentation for our platform:
* core protocol documentation ⚙️
* system diagrams
* user flows

## Audience

This is to be used by other builders that might want to integrate / build on top of our platform (grants, hackathon etc..)

**Comment by rackstar** [comment]
## Tasks


### Core Protocol:

Please complete the following order of priority:

- [x] [Ramm.sol](https://github.com/NexusMutual/smart-contracts/issues/1229)
- [x] [StakingPool.sol](https://github.com/NexusMutual/smart-contracts/issues/1228)
- [x] [Pool.sol](https://github.com/NexusMutual/smart-contracts/issues/1250)
- [x] [Cover.sol](https://github.com/NexusMutual/smart-contracts/issues/1252)
- [x] [StakingProducts.sol](https://github.com/NexusMutual/smart-contracts/issues/1264)
- [ ] [StakingFactory.sol](https://github.com/NexusMutual/smart-contracts/issues/1267) @rackstar
- [ ] [Assessment.sol](https://github.com/NexusMutual/smart-contracts/issues/1265) @MilGard91
- [ ] [IndividualClaims.sol](https://github.com/NexusMutual/smart-contracts/issues/1266)
- [ ] [TokenController.sol](https://github.com/NexusMutual/smart-contracts/issues/1268)


### System Diagram:

TODO

### User Flows:

TODO
