### ISSUE TITLE
V2 Cover unit tests: active cover amount tracking in Cover.sol

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/smart-contracts#278]
**enableActiveCoverAmountTracking**
- [x] Should revert if caller is not emergency admin
- [x] Should revert if active cover amount already committed
- [x] Should revert if not have valid array inputs lengths
- [x] Should enable cover amount tracking
- [x] Should set total active cover in asset for each asset

**commitActiveCoverAmounts**
- [x] Should revert if caller is not emergency admin
- [x] Should revert if active cover amount already committed
- [x] Should commit the active cover amounts

**expireCover**
- [x] Should allow anyone to call this method
- [x] Should revert if cover amount tracking is not enabled
- [x] Should revert if invalid coverId
- [x] Should revert when cover is not due to expire
- [x] Should revert when attempting to expire twice
- [x] Should expire a cover and reduces active cover amount
- [ ] Should expire a cover that had a claim paid out fully
- [ ] Should expire a cover that had partial claim paid out
- [ ] Should expire a cover that had rejected claim
