### ISSUE TITLE
Add mocks/common directory

### ISSUE THREAD

**Issue by rackstar** [NexusMutual/smart-contracts#975]
## Context

Currently there is too much replication of Mocks. We can simplify this by introducing a `mocks/common` directory to house mocks that can be shared by the unit tests.

For the  most commonly used Mocks (i.e PoolMock - MRMockPool, RammMockPool, CLMockPool etc..), it would be ideal to leverage solidity's inheritance. We can implement a base mock that adheres to the interface.

The unit tests can then use this base mock as is or inherit it and override methods depending on their use case.

This should simply and reduce the code significantly as well as having the additional benefit of the mocks adhering to the expected interface.

## Tasks

* [x] create `mocks/common` directory and move common mocks
* [x] create a base `PoolMock` contract that adheres to `IPool` interface
    * [x] Use `PoolMock` contract instead of specific Pool mock contract (override as needed)
* [x] create `EtherRejecterMock` and replace specific ether rejecter mocks
* [x] create `PoolEtherRejecterMock` and replace specific pool ether rejecter mocks

Related issue: https://github.com/NexusMutual/smart-contracts/issues/696
